---
- yum: name="http://mirrors.thzhost.com/remi/enterprise/remi-release-7.rpm" state=present
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"
- yum: name="http://mirrors.thzhost.com/remi/enterprise/remi-release-6.rpm" state=present
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "6"
- yum: name="http://mirrors.thzhost.com/remi/enterprise/remi-release-5.rpm" state=present
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "5"

- ini_file: dest="/etc/yum.repos.d/remi.repo" section="remi" option="enabled" value="1"
