---
- yum: name=epel-release state=present
  when: ansible_os_family == "RedHat"
  tags:
  - packages
  - repo

- yum: name="http://rpms.famillecollet.com/enterprise/remi-release-7.rpm" state=present
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int == 7
  tags:
  - packages
  - repo
- yum: name="http://rpms.famillecollet.com/enterprise/remi-release-6.rpm" state=present
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int == 6
  tags:
  - packages
  - repo
- yum: name="http://rpms.famillecollet.com/enterprise/remi-release-5.rpm" state=present
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int == 5
  tags:
  - packages
  - repo

- yum: name="http://repo.zabbix.com/zabbix/2.2/rhel/7/x86_64/zabbix-release-2.2-1.el7.noarch.rpm" state=present
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int == 7
  tags:
  - packages
  - repo
  - zabbix
- yum: name="http://repo.zabbix.com/zabbix/2.2/rhel/6/x86_64/zabbix-release-2.2-1.el6.noarch.rpm" state=present
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int == 6
  tags:
  - packages
  - repo
  - zabbix
- yum: name="http://repo.zabbix.com/zabbix/2.2/rhel/5/x86_64/zabbix-release-2.2-1.el5.noarch.rpm" state=present
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int == 5
  tags:
  - packages
  - repo
  - zabbix

- ini_file: dest="/etc/yum.repos.d/remi.repo" section="remi" option="enabled" value="1"
