---
- yum: name=epel-release state=present
  when: ansible_os_family == "RedHat"
  tags:
  - packages
  - repo

- yum: name="http://rpms.famillecollet.com/enterprise/remi-release-7.rpm" state=present
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int == 7
  tags:
  - packages
  - repo
- yum: name="http://rpms.famillecollet.com/enterprise/remi-release-6.rpm" state=present
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int == 6
  tags:
  - packages
  - repo
- yum: name="http://rpms.famillecollet.com/enterprise/remi-release-5.rpm" state=present
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int == 5
  tags:
  - packages
  - repo

- ini_file: dest="/etc/yum.repos.d/remi.repo" section="remi" option="enabled" value="1"
